import { useState } from 'react';
import { Shield, FileText, AlertTriangle, CheckCircle } from 'lucide-react';
import { OverviewCard } from './components/OverviewCard';
import { SafetyChart } from './components/SafetyChart';
import { RiskyFeaturesList } from './components/RiskyFeaturesList';
import { FileReportsList } from './components/FileReportsList';
import { FilterPanel } from './components/FilterPanel';
import type { DashboardData, FilterOptions } from './types';
import { AIButton } from './components/AIButton';

function App() {
  const [data, setData] = useState<DashboardData | null>(null);
  const [filters, setFilters] = useState<FilterOptions>({
    showSafe: true,
    showLow: true,
    showFalse: true,
  });

  const handleFileUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const json = JSON.parse(e.target?.result as string);
        setData(json);
      } catch (err) {
        console.error('Failed to parse uploaded JSON:', err);
        alert('Invalid JSON file. Please check the file and try again.');
      }
    };
    reader.readAsText(file);
  };

  // Show file upload UI if no report loaded
  if (!data) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center bg-gray-50 px-4 text-center">
        <Shield className="h-16 w-16 text-primary-600 mb-4" />
        <h1 className="text-3xl font-semibold text-gray-900 mb-2">No Baseline Report Loaded</h1>
        <p className="text-gray-600 mb-6 max-w-md">
          Upload a JSON report generated by the Baseline Toolkit VS Code extension. You can generate
          this report by following the steps in our{' '}
          <a
            href="https://github.com/JonathanSolvesProblems/Baseline-Toolkit#readme"
            target="_blank"
            className="text-primary-600 underline"
          >
            README
          </a>
          .
        </p>

        <label className="cursor-pointer inline-flex items-center px-6 py-3 bg-primary-600 text-white font-medium rounded-lg shadow hover:bg-primary-700 transition-colors">
          <input type="file" accept=".json" onChange={handleFileUpload} className="hidden" />
          Choose JSON File
        </label>
      </div>
    );
  }

  // Dashboard view
  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white shadow-sm border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <div className="flex items-center space-x-3">
              <Shield className="h-8 w-8 text-primary-600" />
              <div>
                <h1 className="text-xl font-semibold text-gray-900">Baseline Toolkit</h1>
                <p className="text-sm text-gray-500">Web Feature Compatibility Dashboard</p>
              </div>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Overview Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
          <OverviewCard title="Total Files" value={data.totalFiles} icon={FileText} />
          <OverviewCard
            title="Safety Score"
            value={`${data.safetyScore}%`}
            icon={CheckCircle}
            color="success"
          />
          <OverviewCard
            title="Safe Features"
            value={data.safeFeatures}
            icon={CheckCircle}
            subtitle={`of ${data.totalFeatures} total`}
            color="success"
          />
          <OverviewCard
            title="Risky Features"
            value={data.riskyFeatures}
            icon={AlertTriangle}
            color="warning"
          />
        </div>

        {/* Main Content */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Left Column */}
          <div className="lg:col-span-2 space-y-8">
            <div className="card">
              <div className="flex items-center justify-between mb-6">
                <h2 className="text-lg font-semibold text-gray-900">Feature Safety Overview</h2>
                <FilterPanel filters={filters} onFiltersChange={setFilters} />
              </div>
              <SafetyChart data={data} filters={filters} />
            </div>

            <div className="card">
              <h2 className="text-lg font-semibold text-gray-900 mb-6">File Analysis</h2>
              <FileReportsList reports={data.reports} filters={filters} />
            </div>
          </div>

          {/* Right Column */}
          <div className="space-y-8">
            <div className="card">
              <h2 className="text-lg font-semibold text-gray-900 mb-6">Risky Features</h2>
              <RiskyFeaturesList reports={data.reports} filters={filters} />
            </div>

            <div className="card">
              <h3 className="text-lg font-semibold text-gray-900 mb-4">Quick Actions</h3>
              <div className="space-y-3">
                <div className="p-3 rounded-lg bg-gray-50 hover:bg-gray-100 transition-colors">
                  <AIButton
                    title="Generate Full Report"
                    getPrompt={() =>
                      `Analyze this baseline report and suggest improvements: ${JSON.stringify(data)}`
                    }
                  />
                  <div className="text-sm text-gray-500 mt-1">
                    Export detailed compatibility analysis
                  </div>
                </div>
                {/* 
                <div className="p-3 rounded-lg bg-gray-50 hover:bg-gray-100 transition-colors">
                  <AIButton
                    title="Check New Files"
                    getPrompt={() =>
                      `Scan these new files for risky features and suggest improvements: ${JSON.stringify(data)}`
                    }
                  />
                  <div className="text-sm text-gray-500 mt-1">Scan workspace for changes</div>
                </div> */}

                {/* <div className="p-3 rounded-lg bg-gray-50 hover:bg-gray-100 transition-colors">
                  <AIButton
                    title="Upgrade Suggestions"
                    getPrompt={() =>
                      `Given this baseline report, provide upgrade suggestions for risky features: ${JSON.stringify(data)}`
                    }
                  />
                  <div className="text-sm text-gray-500 mt-1">
                    Get recommendations for risky features
                  </div>
                </div> */}
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

export default App;
